name: Firmware Size Watcher

on:
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  pull-requests: write

jobs:
  size-report:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v6.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Fix Git Directory Permissions
        run: git config --global --add safe.directory /__w/batear/batear

      - name: Build and Get Size
        id: build
        run: |
          . $IDF_PATH/export.sh
          rm -rf build sdkconfig
          env SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.detector" idf.py set-target esp32s3
          idf.py build
          SIZE_OUTPUT=$(idf.py size 2>&1)
          TOTAL_LINE=$(echo "$SIZE_OUTPUT" | grep -E "^Total ")
          echo "firmware_size=$TOTAL_LINE" >> $GITHUB_OUTPUT

      - name: Comment PR with Size
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## 📉 Firmware Size Report (v1.2.x)
            **Current Total Size:** `${{ steps.build.outputs.firmware_size }}`
            
            > [!TIP]
            > Keeping the binary lean ensures faster OTA updates and more headroom for FFT buffers! 🚀
